### PR TITLE
Slogan pt translation fix

### PR DESCRIPTION
**Pull request by mbcrocci**
Noticed a slight mistake in the slogan translation. 

`reusable` translates into `reutilizável` instead of `usável`, which would be the translation for `usable`.

Great work on the redesign!!

### CODE REVIEW

**Comment by kassane** [comment]
> `reusable` translates into `reutilizável` instead of `usável`, which would be the translation for `usable`.

Well done! Enjoying the opportunity of your contribution.
You could check for me line 55 in this same file and look for the word "Community" and replace it with the translation.

**Review by kassane — CHANGES_REQUESTED** [review]
> `reusable` translates into `reutilizável` instead of `usável`, which would be the translation for `usable`.

Well done! Enjoying the opportunity of your contribution.
You could check line 55 in this same file and look for the word "Community" and replace it with the translation.

**Replace** this:
``{{% div class="container"  style="display:flex;flex-direction:column;justify-content:center;text-align:center; padding: 20px 0;" title="Community" %}}``
to
``{{% div class="container"  style="display:flex;flex-direction:column;justify-content:center;text-align:center; padding: 20px 0;" title="Comunidade" %}}``

**Comment by kristoff-it** [comment]
Thank you @mbcrocci, if you can also apply the change requested by @kassane that would be great, otherwise no worries, I'll merge this PR as-is and apply it myself in a few days.

**Comment by kristoff-it** [comment]
It worked, nice :D

**Pull request merged**
