### PR TITLE
Add turkish translation

### PR DESCRIPTION
**Pull request by meppu**
This pull request includes Turkish translations for the Zig website.

### CODE REVIEW

**Comment by meppu** [comment]
There can be some small typos, I'll patch them with in 2 hours.

**Comment by meppu** [comment]
All done :+1: Waiting for merge.

**Comment by ferhatgec** [comment]
i did the translation at the same time like you, then saw this pr hahaha :D

**Comment by meppu** [comment]
Hey @ferhatgec, it's quite a humorous coincidence that both of us have made Turkish translations simultaneously :D You can contribute by forking my repository and submitting a pull request to fix any errors and enhance the translation.

**Pull request merged**
