### PR TITLE
remove "Source" text from OS column

### PR DESCRIPTION
**Pull request by marler8997**
Removes "Source" from the OS column for the src/bootstrap tarballs.

## CURRENT

image

## NEW

image

### CODE REVIEW

**Comment by BratishkaErik** [comment]
TBH for me this is more confusing than version with "Source", in both English and Russian (especially for the most early releases). Do we really need this change?

**Comment by andrewrk** [comment]
colspan="2", delete some tds, add text-align:center

image

**Comment by marler8997** [comment]
Implemented Andrew's suggestions, here's a preview:
image

Verified it works before bootstrap existed as well, i.e.

image

**Comment by kristoff-it** [comment]
Thank you all for the contributions, I think we should not ask of our users to infer that the source links are tarballs entirely on their own. 

Without the "Source" cell, all that remains is the file name which kinda hints at what it is, but it's not 100% clear in my opinion, so I'm proceeding with this last version. 

Thank you for your work Johnny

**Pull request merged**
