### PR TITLE
Add a link to Exercism track

### PR DESCRIPTION
**Pull request by booniepepper**
Exercism is a not-for-profit organisation registered in the UK. The Zig track was soft-launched earlier this year, and is now stable and growing with more than 1000 students!

~~P.S. The site is only available in English like Ziglearn and Ziglings, but should I add it to pages for other languages I can write?~~ Yes

P.P.S. if anyone arrives here interested in contributing to Zig on Exercism, go to https://github.com/exercism/zig

### CODE REVIEW

**Comment by booniepepper** [comment]
P.S. the Zig track at Exercism is currently using Zig 0.10.1, but will be updated to 0.11 shortly https://github.com/exercism/zig/issues/244

**Comment by kristoff-it** [comment]
Please add the link also to the other languages, the various maintainers will then provide a translation when they happen to check the Zig website. 

Thanks.

**Comment by BratishkaErik** [comment]
Please note that it has optional ChatGPT integration in premium version https://exercism.org/premium (just in case if you'd dislike it)

**Comment by booniepepper** [comment]
Added the link to all the learn pages

BTW we got Zig 0.11 live on Exercism a few hours ago: https://github.com/exercism/zig/issues/244

**Comment by booniepepper** [comment]
Added the link to all the learn pages

BTW we got Zig 0.11 live on Exercism a few hours ago: https://github.com/exercism/zig/issues/244

**Comment by booniepepper** [comment]
How's it look? @kristoff-it

**Comment by kristoff-it** [comment]
@booniepepper there's a copy paste error in the korean version, once you fix it I'll be happy to merge the PR. Thank you!

**Comment by booniepepper** [comment]
@kristoff-it Thanks for the patience. I updated and also rebased my PR

**Pull request merged**
