### PR TITLE
Improve appearance of website

### PR DESCRIPTION
**Pull request by r2453**
I think Zig would benefit from a better-looking website. I have added some CSS and Javascript to improve its appearance. The most significant changes I have made are changing the font and adding a sticky navigation bar. A screenshot is below.

firefox_screenshot_2018-06-27t09-43-57 643z

### CODE REVIEW

**Comment by 0joshuaolson1** [comment]
The sticky bar text seems a bit small - is it readable on mobile?

**Comment by tiehuis** [comment]
Had a look and I think in general it looks good. Works fine on mobile and without js too.

Sometime in the future it would be valuable to decide the overall site/project style formally and apply that everywhere (such as documentation/release-notes) and going forward on new pages.

**Comment by andrewrk** [comment]
Thanks for doing this! I merged it and pushed it, with these modifications:
 * Remove the sticky bar and associated javascript. I'd like to avoid javascript on ziglang.org.
    - note: the plan for syntax highlighting in the lang ref and documentation will be static syntax highlighting when the docs are compiled
 * Download the font from google and include on ziglang.org. I'd like to avoid third party http requests on ziglang.org.
 * Made the nav items underline on hover
 * Moved the "plz donate" footer to above the fold on the download page.

I pushed this and made this live, but now I'm confused, as the style sheet is not being applied to the HTML, even though it works when I test locally.

**Comment by andrewrk** [comment]
fixed 77749aecd4d0e5e3ffc6e05ddb47e73ef991e582
See https://github.com/s3tools/s3cmd/issues/198

**Pull request merged**
