### PR TITLE
Fix command in getting started page

### PR DESCRIPTION
**Pull request by tisonkun**
Other languages' versions are correct.

### CODE REVIEW

**Comment by tisonkun** [comment]
cc @andrewrk

**Review by Fonsan — APPROVED** [review]
Thanks, just ran into this and can confirm this is correct

**Comment by kristoff-it** [comment]
The website tracks master branch and latest Zig has `zig init` as the only project initialization command.

**Comment by Fonsan** [comment]
I see, how can we improve the experience for people discovering zig? Most will install the latest stable release through a package manager and run into this and possibly other divergences introduced in the master branch. The main page even mentions latest release (currently `0.11`) and although on the "learn" documentation gets separate links to master and latest stable the "Getting started" does not.

image

**Pull request closed without merging**
