### PR TITLE
Various fixes + add localization support for few strings + add Russian translation

### PR DESCRIPTION
**Pull request by BratishkaErik**

### CODE REVIEW

**Comment by BratishkaErik** [comment]
https://ziglang.org/fr/learn/getting-started/ and other affected translated versions:

Before 9c1b1d24f28e774102e6df8e32f67b577bf44247: 
изображение

After 9c1b1d24f28e774102e6df8e32f67b577bf44247: (It is my local copy of the site, that's why you can see Russian localization although this is a newer commit 8ced9ae0713dfe5ae9076c0330f97105be8cc958.)
Screenshot_20220619_005717

**Comment by BratishkaErik** [comment]
https://ziglang.org/es/news/ and other translated versions:

Before 87b93d31f11410327f269b16aa70cc8c7e14b932:

изображение

After:
изображение

**Comment by BratishkaErik** [comment]
https://ziglang.org/es/learn/ and other translated versions: fix displaying for mobile devices

Before bb06e53bbe5adaeba2af8c31887266c5d4130c4d:
Screenshot_20220619-010444_Fennec

After:
Screenshot_20220619-010504_Fennec

**Comment by C-BJ** [comment]
@kristoff-it

**Comment by kristoff-it** [comment]
Hi, thank you for your contribution. I'm going to merge this but I will revert the changes to the "this page was translated by the zig community" bit as that's meant to stay english on all pages.

**Pull request merged**
