### PR TITLE
Smaller icon implementation, separate from logo

### LINKED ISSUE #27: Tiny logo
Inspired by https://github.com/edent/SuperTinyIcons, I made a hand-written SVG of the Zig logo that is ~600 bytes. This should make it suitable for embedding in the language reference documentation, etc. Using an SVG optimizer, pushes it down to ~500 bytes, but it's not easy to tweak in that form. For comparison, the current logo is ~3.8 KB.

While it's not a pixel-perfect recreation of the original logo, it is intended to look the same at a cursory glance. Changes:
- Omitted text since it can be replaced with markup.
- Slightly reduced the aspect ratio to 3:2.

If there is interest in using this logo, I will start a PR that incorporates it into the website and documentation.

---

Current logo (rasterized):
image

Tiny logo (rasterized):
image

SVG source: https://gist.github.com/jayschwa/1ef7b11ae2e82e78d3ac434140113a2d

### PR DESCRIPTION
**Pull request by jayschwa**
zig-icon.svg is a new, hand-written implementation. It is embedded in
zig-logo.svg (icon with title text), which has also been minified.

Closes #27

### CODE REVIEW

**Comment by jayschwa** [comment]
What is the font-face? I can try using SVG's `<text>`.

**Comment by andrewrk** [comment]
Your guess is as good as mine. [Here are the materials I got from 99-designs](http://superjoe.s3.amazonaws.com/temp/zig-logo-files.zip). It looks to me like the author rendered the font into vectors.

**Comment by andrewrk** [comment]
Wouldn't that have the same problem though - depending on the system installed fonts?

**Comment by andrewrk** [comment]
I think it probably makes sense to have one without the text, and one with the text. The 600 byte one would be the favicon, and generally be available for people to use for any purpose when they only want an icon, and the other one would include the text, and be the banner logo on ziglang.org. Does that seem reasonable?

**Comment by jayschwa** [comment]
@andrewrk, I pushed some updates to this branch. `zig-icon.svg` is just the new icon without text. `zig-logo.svg` is `zig-icon.svg` embedded plus text. I didn't recreate the text at all. I took what was there already and just minified it. `zig-logo.svg` went from 3.9 KB to 1.5 KB with these changes.

image

**Comment by andrewrk** [comment]
Thanks for keeping the text. I love it!

**Pull request merged**
