### PR TITLE
new community page

### PR DESCRIPTION
**Pull request by slimsag**
@kristoff-it I only played around with this for a few hours in case you don't like it and want to throw it out 😛

In some ways, I think this is better - but in other ways, I feel like it doesn't "fit" into the Zig site's current style, the information density is bad I think, so I'm pretty torn on it myself and debated whether or not I should send the PR TBH. Maybe it's got some interesting ideas you can pull for inspiration in any case.

One nifty thing was pulling off the filtering buttons in pure CSS.

image

image

Signed-off-by: Stephen Gutekanst <stephen@hexops.com>

### CODE REVIEW

**Comment by slimsag** [comment]
Thoughts for some improvements I'll try later:

* Maybe try ditching the icons all together and seeing how that looks? 
* Don't round corners, looks out of place with the rest of the site
* Background colors of the cards feel "off", they make the cards pop out of the page. Instead, maybe do _no_ background color but rather just a border for the cards. Description area might still have a subtle background color.

**Comment by AliChraghi** [comment]
nice! looks perfect
but seem you have forgotten the light mode

image

also as you said rounded corners is't coordinated with the rest of the site. i think this feel better

image

**Comment by slimsag** [comment]
Planning to pick this back up this weekend, sorry for delay!

**Comment by slimsag** [comment]
Merged `master` into this branch as it was quite out of date, I can squash history later.

Not sure if you'll all dislike this (totally fine if so!), but my thinking is:

* Make each card super minimal, like just a title+link+description
    * Ok.. also include the people behind it, because giving credit / showing ownership and moderation of communities is important here :)
* Structure the page around a _user_ coming here: instead of giving them a complete info dump of every community and every possible link / way you could interact with that community (wow that's a lot of info!) let's have categories of things that users may want to do: learn zig, get help, join a live chat, get news, etc.
* Each community that provides one of those _services_ can list themselves in that category.

Not finished, but here's how it looks atm - feedback appreciated:

image

**Comment by AliChraghi** [comment]
I like this. It may be better with a thicker border ('2px' or '3px')

**Comment by slimsag** [comment]
@AliChraghi yeah I'll try that out, also note it looks different when viewed outside of screenshot form (that screenshot is super long and so makes the padding / borders look strange compared to when viewing on e.g. a laptop display)

**Pull request closed without merging**
