### PR TITLE
Add `s390x-linux` to the download page.

### PR DESCRIPTION
**Pull request by alexrp**
ref: https://github.com/ziglang/zig/issues/21402

### CODE REVIEW

**Comment by andrewrk** [comment]
ok, I have a serious question for you though... can you name one person on earth who wants this?

**Comment by alexrp** [comment]
🤔 There at least seems to be... non-zero interest in it:

* https://github.com/ziglang/zig/issues/21076
* https://github.com/ziglang/zig/issues/14118
* https://github.com/ziglang/zig/issues/3655 (not Linux, granted, but still s390x)

I mean, yeah, it's not a lot. But s390x is an actively used and still evolving architecture in the enterprise/mainframe space; the most recent architecture revision with hardware was in 2022, with the newest revision having been announced this year. IBM are consistently contributing s390x work to Linux, binutils/GCC, LLVM, QEMU, etc. They also recently started investing more into .NET on s390x, and even Node.js provides prebuilt s390x binaries nowadays. So I don't see any signs of it going anywhere anytime soon. Contrast with some of the other targets we have on the page - `x86-windows`, `x86-linux`, and `x86_64-macos` - which are slowly but surely on their way out.

I think part of the reason you don't hear much about s390x is that it exists in a somewhat isolated world; because of the cost of these systems, they're just not very accessible or relevant to us mere mortals. Zig getting a foot in the door will probably require proactive effort on our part, and having `s390x-linux` on the download page sends an unambiguous signal that Zig supports this platform. I would hope that companies in that world would feel more confident choosing Zig as a result. My more wishful thinking here is that this could also benefit the ZSF in the long term because these are companies with exceptionally deep pockets. But who knows. 🤷

**Comment by andrewrk** [comment]
Alright, good enough for me!

**Comment by andrewrk** [comment]
Ended up reverting this due to awkwardness with website deploys. Please allow me to convert these CI scripts to zig code and then we can re-land this. I'm also planning to remove the part where the tarball script makes edits to the website repo.

**Comment by alexrp** [comment]
Sure, sounds reasonable!

**Pull request merged**
