### PR TITLE
Make new perf page use hugo templates

### PR DESCRIPTION
**Pull request by rudedogg**
This adds Hugo templates to the website so the new https://ziglang.org/perf/ page more closely resembles ziglang.org.

One major change I made when compared to the main site, is increasing the body max-width to 1600px. I did this so the chart text is easier to read. Since it's not primarily a text page, this shouldn't have any negative affects on readability.

I still need to update the chart colors so they are readable for users of both the dark and light system color themes. I'll try and get to that this weekend so I can begin working on the chart structure/designs.

Here's what I have so far:
image
---------------------------------------
image

As you can see the chart colors need changes with the dark background, so I've made this a draft until I fix them.

Let me know if you'd like anything changed or done differently, thanks!

### CODE REVIEW

**Comment by rudedogg** [comment]
I made a few changes:
- Hovering a data point causes it's dot radius to become larger, and filled with the line color
- The hover text is light or dark depending on the color scheme

The use of `currentColor` to get a light color when in dark mode, and a dark color in light mode is mentioned here: https://web.dev/prefers-color-scheme/#use-currentcolor-for-inline-svgs

It works for me on Safari, but is probably worth double checking.

----------------------------------------------------------------------------

### Dark color scheme
image

#### Hovering a data point
image

### Light color scheme
image

#### Hovering a data point
image


I'm moving this out of draft since I think it's ready now.

**Comment by matu3ba** [comment]
Looks awesome. Minor nit: The contrast of the yellow graph higher in comparison to the other graphs. Is that intended? To me it looks like the text `cache misses` is abit darker, but that may just be due to relative size.

**Comment by rudedogg** [comment]
> Looks awesome. 

Thanks!

> Minor nit: The contrast of the yellow graph is higher in comparison to the other graphs (especially in dark mode). Is that intended? 

Oh yeah I see what you mean, in dark mode that line really stands out versus the rest.

I want to make some structure and color changes to the graphs in an upcoming PR, but I held off on adjusting the colors so far (besides turning off the blend-mode stuff). In the next PR I'll try and use a perceptually uniform color space to grab colors to fix that.

> Related to that: To me it looks like the text `cache misses` is abit darker than the yellow graph, but that may just be due to relative size.

Yeah this must be from the sizing, or maybe the neighboring things making it appear darker? I see the same thing though.

> The images you posted also have some offset, but I guess thats due to how you captured the images or independent of your change.

Shoot yeah, that must be from how I captured the screenshots. The layout is the same for light and dark color schemes. I'll see if I can use the web inspector to take any other whole-page screenshots so they'll be consistent.

**Comment by andrewrk** [comment]
Looks great!

I just want to check with @kristoff-it about the navigation bar- I think we probably want to keep the standard navigation bar the same as the rest of the website, and have the perf related links inside the main body.

The image and the word "PERFORMANCE" at the top look great though, those can stay for sure.

**Comment by kristoff-it** [comment]
I'm mildly in favor of keeping the usual menu but in either case I do realize that there some work that needs to be done in terms of navigation. Just for the sake of consistency I would put the perf specific navigation inside the main content div. At that point IMO we can merge and then you'll have to give me a bit of time to find a nice way to link to perf/ from the main site navigation.

**Comment by andrewrk** [comment]
Merging, leaving the nav bar improvements to be made as a follow-up.

**Pull request merged**
