### PR TITLE
Perf chart updates

### PR DESCRIPTION
**Pull request by rudedogg**
**This is a work-in-progress.**

**There are still quite a few important things I want to try or do:**

- [x] Hovering data points near the right edge of the screen causes them to be cut off 
- [x] Filter by date
- [ ] Use localized dates, if easy enough with vanilla JS
- [ ] Try out making X-Axis ticks be per-commit
- [ ] Get rid of the duplicated chart X-axis/labels, and make them share a single x-axis since it is the same for all measurements
- [ ] The CSS is pretty bad, I need to choose better/less specific selectors and clean things up
- [x] I've added a new Javascript dependency for the "development UI" that isn't really required. Need to redo that UI with vanilla javascript and remove it
- [ ] Add a new matrix chart to the top of the page.
   This will hopefully be the at-a-glance way of checking for regressions.
- [ ] Go over all the math stuff to look for mistakes
- [ ] Switch to not using the ziglang.org homepage navbar, and put the nav links in the body instead
- [ ] Pick per-measurement colors
- [ ] Experiment more with using the built-in d3 color scales to show changes
- [ ] Other bugs/issues I'm forgetting

I wanted to open a PR since this is running a little longer than I anticipated. I need to jump back on another project for a short time, and will return to finishing this soon!

----------------------------

Here are some screenshots of where things are now:
image
Tooltip:
image

### CODE REVIEW

**Comment by andrewrk** [comment]
Those screenshots are looking real nice :fire:

**Comment by andrewrk** [comment]
any chance this could be brought to a mergeable state, with future improvements done separately?

**Comment by rudedogg** [comment]
> any chance this could be brought to a mergeable state, with future improvements done separately?

Yes! I will get it mergable this weekend – hopefully tomorrow. 

I broke the code that determines which data point is being hovered, so I'll get that working again. That, plus a couple small things, and it should be good enough to play around with.

**Comment by rudedogg** [comment]
I think this should be mergable now. I fixed the hovering thing, which was the main annoyance I ran into when using it. Also fixed some errors and hopefully some date filtering edge cases.

I apologize in advance for any bugs, it's a lot of JS so I'm sure there will be a few!

**Comment by andrewrk** [comment]
Let's try it out!

**Pull request merged**
