### PR TITLE
Adding the french translation.

### PR DESCRIPTION
**Pull request by KaneRoot**
Hello, this is my first commit here! :)

In this translation:
- I did change the links so they should be okay (they were broken a few days ago)
- some paragraphs were reworded for a better understanding
- links to English material were announced with "(EN)"
- I encountered "501(c)(3)" sometimes, and it probably has no implication for people outside the USA but I let this code just in case
- I rebased everything so you just have a single commit to fast-forward
- I re-read it twice, but I guess there is still plenty of room for improvement, so don't hesitate to contact me for changes

I think that's about it…

Is there anything else I need to do?

### CODE REVIEW

**Comment by kristoff-it** [comment]
Hi, thank you very much for your contribution and sorry for the delay.

Let's have a second set of eyes on the tranlation while I double check the links and then we can merge.

@Sahnvour would you mind taking a look? Thanks!

**Comment by kristoff-it** [comment]
Done checking the links, all seems in order, great job there!!

**Comment by Sahnvour** [comment]
Sure, I'll take a look this week.

**Comment by Sahnvour** [comment]
Sorry about the delay, finally had time to take a look.

There is room for improvements here and there obviously, but looks good to me overall.
I noticed missing translations for some headers/buttons/menus, the most important being:
- `Source Code` and `Join a community` in the main menu
- Stuff around the `Get started` button on the main page

The main question I have right now is whether we should translate everything, including technical terms. There are some that are very rarely used in their french version, when they have one. But that's outside my area of knowledge, and not a blocker.

**Review by Sahnvour — APPROVED** [review]

**Comment by kristoff-it** [comment]
Thank you for the feedback, if that's the case then, let's merge!

**Pull request merged**
